language: python
python:
    - "3.7"
install:
    - pip install -r requirements.txt
    - pip install pytest-cov codecov # Install packages for code coverage report
script:
    - pytest --cov=sim test # Point to sim directory