### DOCK AND BIKE ###
CONDITIONS = ['good', 'fair', 'poor', 'not in service']


### BIKE CONSTANTS ###
CLASSIC_BASE_RATE = 3.50
CLASSIC_ADD_RATE = 0.10

ELECTRIC_BASE_RATE = 5.25
ELECTRIC_ADD_RATE =  0.20
ELECTRIC_MAX_CHARGE = 100